mapa={
"Maringá": {"Santa Fé": 50, "Marialva": 15, "Astorga": 35},
"Marialva": {"Maringá": 15, "Mandaguari": 10},
"Mandaguari": {"Marialva": 10, "Jandaia do Sul": 20, "Arapongas": 25},
"Jandaia do Sul": {"Mandaguari": 20, "Arapongas": 30, "Guaravera": 45},
"Arapongas": {"Guaravera": 35, "Cambé": 40, "Astorga": 20, "Jaguapitã": 25, "Mandaguari": 25, "Jandaia do Sul": 30},
"Guaravera": {"Jandaia do Sul": 45, "Arapongas": 35, "Londrina": 25},
"Cambé": {"Londrina": 10, "Arapongas": 40, "Jaguapitã": 35, "Sertanópolis": 30, "Bela Vista do Paraíso": 20},
"Londrina": {"Sertanópolis": 25, "Bela Vista do Paraíso": 10, "Cambé": 10, "Ibiporã": 15, "Guaravera": 25},
"Ibiporã": {"Londrina": 15, "Sertanópolis": 20, "Uraí": 35, "Cornélio Procópio": 50, "Assaí": 45},
"Assaí": {"Uraí": 15, "Cornélio Procópio": 20, "Ibiporã": 45, "São Sebastião da Amoreira": 25},
"São Sebastião da Amoreira": {"Assaí": 25, "Nova Santa Bárbara": 30, "Uraí": 30, "Cornélio Procópio": 25},
"Nova Santa Bárbara": {"São Sebastião da Amoreira": 30},
"Uraí": {"São Sebastião da Amoreira": 30, "Cornélio Procópio": 25, "Assaí": 15, "Ibiporã": 35},
"Cornélio Procópio": {"Uraí": 25, "Assaí": 20, "São Sebastião da Amoreira": 25},
"Sertanópolis": {"Bela Vista do Paraíso": 15, "Cambé": 30, "Londrina": 25, "Ibiporã": 20},
"Bela Vista do Paraíso": {"Sertanópolis": 15, "Cambé": 20, "Londrina": 10},
"Jaguapitã": {"Arapongas": 25, "Astorga": 20, "Cambé": 35},
"Santa Fé": {"Astorga": 20, "Maringá": 50},
"Astorga": {"Jaguapitã": 20, "Santa Fé": 20, "Maringá": 35, "Arapongas": 20, "Cambé": 40},
}