mapa={
"Maringá": ["Santa Fé", "Marialva", "Astorga"],
"Marialva": ["Maringá", "Mandaguari"],
"Mandaguari": ["Marialva", "Jandaia do Sul", "Arapongas"],
"Jandaia do Sul": ["Mandaguari", "Arapongas", "Guaravera"],
"Arapongas": ["Guaravera", "Cambé", "Astorga", "Jaguapitã", "Mandaguari", "Jandaia do Sul"],
"Guaravera": ["Jandaia do Sul", "Arapongas", "Londrina"],
"Cambé": ["Londrina", "Arapongas", "Jaguapitã", "Sertanópolis", "Bela Vista do Paraíso"],
"Londrina": ["Sertanópolis", "Bela Vista do Paraíso", "Cambé", "Ibiporã", "Guaravera"],
"Ibiporã": ["Londrina", "Sertanópolis", "Uraí", "Cornélio Procópio", "Assaí"],
"Assaí": ["Uraí", "Cornélio Procópio", "Ibiporã", "São Sebastião da Amoreira"],
"São Sebastião da Amoreira": ["Assaí", "Nova Santa Bárbara", "Uraí", "Cornélio Procópio"],
"Nova Santa Bárbara": ["São Sebastião da Amoreira"],
"Uraí": ["São Sebastião da Amoreira", "Cornélio Procópio", "Assaí", "Ibiporã"],
"Cornélio Procópio": ["Uraí", "Assaí", "São Sebastião da Amoreira"],
"Sertanópolis": ["Bela Vista do Paraíso", "Cambé", "Londrina", "Ibiporã"],
"Bela Vista do Paraíso": ["Sertanópolis", "Cambé", "Londrina"],
"Jaguapitã": ["Arapongas", "Astorga", "Cambé"],
"Santa Fé": ["Astorga", "Maringá"],
"Astorga": ["Jaguapitã", "Santa Fé", "Maringá", "Arapongas", "Cambé"],
}